// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaGp6NKP3tPDnSdscsfWX7p391NSV6DGg',
    appId: '1:339394052695:web:2c352685a1b2d802a71912',
    messagingSenderId: '339394052695',
    projectId: 'ubuntu-interiors-cdbde',
    authDomain: 'ubuntu-interiors-cdbde.firebaseapp.com',
    storageBucket: 'ubuntu-interiors-cdbde.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4QD5xYsDrbdcUZhRfVk7hY0Lbe0WOC9w',
    appId: '1:893864659378:android:a663b233f6cc2414ca3cab',
    messagingSenderId: '893864659378',
    projectId: 'ubuntu-interiors-1e073',
    storageBucket: 'ubuntu-interiors-1e073.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSmjS1N-nR4qaYfixd3qwXsonnfP4zx34',
    appId: '1:339394052695:ios:0212de529acdb391a71912',
    messagingSenderId: '339394052695',
    projectId: 'ubuntu-interiors-cdbde',
    storageBucket: 'ubuntu-interiors-cdbde.firebasestorage.app',
    iosBundleId: 'com.example.ubuntuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSmjS1N-nR4qaYfixd3qwXsonnfP4zx34',
    appId: '1:339394052695:ios:0212de529acdb391a71912',
    messagingSenderId: '339394052695',
    projectId: 'ubuntu-interiors-cdbde',
    storageBucket: 'ubuntu-interiors-cdbde.firebasestorage.app',
    iosBundleId: 'com.example.ubuntuApp',
  );
}